Remove punctuation which becomes part of the url (#284)
In colab and likely other applications, the period is incorrectly bound into the url, which is then invalid and produces a 404

DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or
explicitly create credential and re-run the application. For more
information, please see
https://developers.google.com/accounts/docs/application-default-credentials.