Fix "AttributeError: 'str' object has no attribute 'get'"
* The current code assumes that response_data will always be a dict or a mapping of some kind, but it is possible for response_data to be a str.
* When response_data is a str, then the function fails on `response_data.get("error")` but the error response is swallowed so the user doesn't know why it failed. The user just sees: `AttributeError: 'str' object has no attribute 'get'` and a stacktrace
* This is a quick and dirty fix that guarantees the `.get` call will succeed, and the result is that the error response bubbles up to the user.
* Feel free to make this fix more robust/clean.